version: '3'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=team-member-projects
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysql

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mysql
    ports:
      - "8083:80"
    container_name: phpmyadmin
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local